# Generated by Django 5.1.2 on 2024-11-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjTraders', '0002_alter_customer_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
